package com.example.mycity.ui.theme

import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val cityLightPrimary = Color(0xFF825500)
val cityLightOnPrimary = Color(0xFFFFFFFF)
val cityLightPrimaryContainer = Color(0xFFFFDDAE)
val cityLightOnPrimaryContainer = Color(0xFF2A1800)
val cityLightSecondary = Color(0xFF6F5B40)
val cityLightOnSecondary = Color(0xFFFFFFFF)
val cityLightSecondaryContainer = Color(0xFFFADEBC)
val cityLightOnSecondaryContainer = Color(0xFF271904)
val cityLightTertiary = Color(0xFF516440)
val cityLightOnTertiary = Color(0xFFFFFFFF)
val cityLightTertiaryContainer = Color(0xFFD3EABC)
val cityLightOnTertiaryContainer = Color(0xFF102004)
val cityLightError = Color(0xFFBA1B1B)
val cityLightErrorContainer = Color(0xFFFFDAD4)
val cityLightOnError = Color(0xFFFFFFFF)
val cityLightOnErrorContainer = Color(0xFF410001)
val cityLightBackground = Color(0xFFFCFCFC)
val cityLightOnBackground = Color(0xFF1F1B16)
val cityLightSurface = Color(0xFFFCFCFC)
val cityLightOnSurface = Color(0xFF1F1B16)
val cityLightSurfaceVariant = Color(0xFFF0E0CF)
val cityLightOnSurfaceVariant = Color(0xFF4F4539)
val cityLightOutline = Color(0xFF817567)
val cityLightInverseOnSurface = Color(0xFFF9EFE6)
val cityLightInverseSurface = Color(0xFF34302A)
val cityLightPrimaryInverse = Color(0xFFFFB945)


val cityDarkPrimary = Color(0xFFFFB945)
val cityDarkOnPrimary = Color(0xFF452B00)
val cityDarkPrimaryContainer = Color(0xFF624000)
val cityDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val cityDarkSecondary = Color(0xFFDDC3A2)
val cityDarkOnSecondary = Color(0xFF3E2E16)
val cityDarkSecondaryContainer = Color(0xFF56442B)
val cityDarkOnSecondaryContainer = Color(0xFFFADEBC)
val cityDarkTertiary = Color(0xFFB8CEA2)
val cityDarkOnTertiary = Color(0xFF243516)
val cityDarkTertiaryContainer = Color(0xFF3A4C2B)
val cityDarkOnTertiaryContainer = Color(0xFFD3EABC)
val cityDarkError = Color(0xFFFFB4A9)
val cityDarkErrorContainer = Color(0xFF930006)
val cityDarkOnError = Color(0xFF680003)
val cityDarkOnErrorContainer = Color(0xFFFFDAD4)
val cityDarkBackground = Color(0xFF1F1B16)
val cityDarkOnBackground = Color(0xFFEAE1D9)
val cityDarkSurface = Color(0xFF1F1B16)
val cityDarkOnSurface = Color(0xFFEAE1D9)
val cityDarkSurfaceVariant = Color(0xFF4F4539)
val cityDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val cityDarkOutline = Color(0xFF9C8F80)
val cityDarkInverseOnSurface = Color(0xFF1F1B16)
val cityDarkInverseSurface = Color(0xFFEAE1D9)
val cityDarkPrimaryInverse = Color(0xFF825500)
